#!/bin/bash

#set job requirements
#SBATCH -n 1 
#SBATCH -p normal
#SBATCH -t 00:10:00

#download R
module load 2022
module load R/4.2.1-foss-2022a
Rscript --no-save --slave run_and_save.R 5 10 random 1




