#!/bin/bash

#set job requirements
#SBATCH -n 1 
#SBATCH -p normal
$SBATCH --cpus-per-task = 3
#SBATCH -t 05:00:00

#download R
module load 2021
module load R/4.1.0-foss-2021a
for graph in "random" "circle"
    do 
    Rscript --no-save --slave run_and_save.R 5 10 $graph 3
    Rscript --no-save --slave results_main.R 5 10 $graph 3
done




